export const WEBEAZY_EDITOR_ROADMAP = {
  philosophy: [
    "Designer-first visual editing",
    "Code remains available for advanced users",
    "Projects are local-first and portable",
    "Every visual action maps to structured HTML/CSS data",
  ],
  v1: [
    "Project lifecycle: create, save, open, exit",
    "Persistent JSON project format",
    "Visual canvas with select, section and shape tools",
    "Locked-by-default visual elements with explicit unlock",
    "Move and resize unlocked elements",
    "Layers/tree panel",
    "Properties inspector for dimensions, spacing, colors, borders and typography",
    "Undo/redo history",
    "Autosave and dirty-state indicator",
    "Responsive desktop/tablet/mobile canvas modes",
    "Page management and page settings",
    "Asset manager with local file references",
    "HTML/CSS/JS code view",
    "Live preview",
    "Export project JSON",
    "Export static HTML/CSS/JS",
  ],
  v1_5: [
    "Reusable components/blocks",
    "Snap-to-grid and alignment guides",
    "Keyboard shortcuts",
    "Context menu",
    "Duplicate/copy/paste",
    "Style presets and variables",
    "Custom JavaScript library imports",
    "Plugin architecture",
  ],
  later: [
    "GitHub sync",
    "Netlify sync/deployment",
    "Advanced component marketplace",
    "Optional AI assistance",
    "Cloud collaboration",
  ],
} as const;
