import type { CSSProperties } from "react";
import { ArrowLeft, Monitor, Smartphone, Tablet } from "lucide-react";
import type { DemoBlock } from "@/lib/hackathon/ai-prototype";
type Viewport="desktop"|"tablet"|"mobile"; const viewportWidths:Record<Viewport,number>={desktop:1120,tablet:760,mobile:390};
function canvasHeight(bs:DemoBlock[]){return Math.max(900,...bs.map(b=>b.y+b.height+100));}
function style(b:DemoBlock):CSSProperties{return{position:"absolute",left:b.x,top:b.y,width:b.width,height:b.height,background:b.background,color:b.color,borderRadius:b.radius,zIndex:1,overflow:"hidden",boxSizing:"border-box"};}
function content(b:DemoBlock){if(b.type==="image"&&b.src)return <img src={b.src} alt={b.name} className="h-full w-full object-cover"/>;if(b.type==="heading")return <div className="h-full overflow-hidden whitespace-pre-wrap break-words text-[48px] font-bold leading-[1.05]">{b.text}</div>;if(b.type==="button")return <div className="flex h-full items-center justify-center gap-2 px-5 text-sm font-semibold">{b.text}<span>→</span></div>;if(b.type==="card")return <div className="flex h-full flex-col justify-end p-5 text-base font-semibold">{b.text}</div>;return <div className="h-full overflow-hidden whitespace-pre-wrap break-words text-base leading-6">{b.text}</div>}
export function GeneratedSitePreview({blocks,businessName,viewport,onBack}:{blocks:DemoBlock[];businessName:string;viewport:Viewport;onBack:()=>void}){const width=viewportWidths[viewport],height=canvasHeight(blocks);return <div className="webeazy-preview-shell flex h-full min-h-0 flex-col bg-[#080a0c] text-white"><div className="sticky top-0 z-30 flex h-14 shrink-0 items-center justify-between border-b border-white/10 bg-[#0f1217]/95 px-4 backdrop-blur"><div className="flex items-center gap-3"><button onClick={onBack} className="rounded-lg p-2 text-white/55 hover:bg-white/5 hover:text-white"><ArrowLeft className="size-4"/></button><div><div className="text-xs font-semibold">WebEazy Preview</div><div className="text-[10px] text-white/35">{businessName} · Layout preserved from canvas</div></div></div><div className="flex items-center gap-2 text-[10px] text-white/45">{viewport==="desktop"?<Monitor className="size-3.5"/>:viewport==="tablet"?<Tablet className="size-3.5"/>:<Smartphone className="size-3.5"/>}{viewport}</div></div><div className="min-h-0 flex-1 overflow-auto"><div className="mx-auto min-w-max p-8"><div className="relative overflow-hidden bg-[#0c1011] shadow-[0_30px_100px_rgba(0,0,0,.55)]" style={{width,height}}>{blocks.map(b=><div key={b.id} style={style(b)}>{content(b)}</div>)}</div></div></div></div>}
export function buildGeneratedSiteExportHtml(businessName:string,blocks:DemoBlock[]){const esc=(v:string)=>v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");const body=blocks.map(b=>{const css=`position:absolute;left:${b.x}px;top:${b.y}px;width:${b.width}px;height:${b.height}px;background:${b.background};color:${b.color};border-radius:${b.radius}px;box-sizing:border-box;overflow:hidden;z-index:1;`;let inner="";if(b.type==="image"&&b.src)inner=`<img src="${esc(b.src)}" alt="${esc(b.name)}" style="width:100%;height:100%;object-fit:cover;display:block">`;else if(b.type==="heading")inner=`<div style="font-size:48px;font-weight:700;line-height:1.05;white-space:pre-wrap">${esc(b.text)}</div>`;else if(b.type==="button")inner=`<div style="height:100%;display:flex;align-items:center;justify-content:center;font-weight:600">${esc(b.text)} →</div>`;else if(b.type==="card")inner=`<div style="height:100%;display:flex;align-items:flex-end;padding:20px;font-weight:600">${esc(b.text)}</div>`;else inner=`<div style="white-space:pre-wrap;line-height:1.5">${esc(b.text)}</div>`;return `<div style="${css}">${inner}</div>`;}).join("");const height=canvasHeight(blocks);return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(businessName)}</title></head><body style="margin:0;background:#080a0c;color:white"><main style="position:relative;width:1120px;min-height:${height}px;margin:0 auto;background:#0c1011">${body}</main></body></html>`;}
